import { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { api, Project } from '../services/api';
import Integrated3DViewer from '../components/Integrated3DViewer';
import Chatbot from '../components/Chatbot';

const ProjectDetailsPage = () => {
  const { projectId } = useParams<{ projectId: string }>();
  const navigate = useNavigate();
  const [project, setProject] = useState<Project | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [activeTab, setActiveTab] = useState<'viewer' | 'details' | 'settings'>('viewer');

  useEffect(() => {
    if (projectId) {
      fetchProject();
    }
  }, [projectId]);

  const fetchProject = async () => {
    if (!projectId) return;
    
    setLoading(true);
    setError('');
    
    try {
      const mockProject: Project = {
        ProjectID: projectId,
        UserID: 'mock-user',
        ProjectName: `AI Generated Room ${projectId}`,
        Description: 'Beautiful bedroom space generated by AI with modern 3D visualization',
        CreatedTime: Date.now().toString(),
        UpdatedTime: Date.now().toString()
      };
      
      setProject(mockProject);
    } catch (err: any) {
      console.error('Error fetching project:', err);
      setError('Failed to load project. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const handleBack = () => {
    navigate('/dashboard');
  };

  const formatDate = (timestamp: string | number) => {
    let date: Date;
    
    if (typeof timestamp === 'string') {
      const numTimestamp = parseInt(timestamp, 10);
      if (!isNaN(numTimestamp)) {
        date = new Date(numTimestamp * 1000);
      } else {
        date = new Date(timestamp);
      }
    } else {
      date = new Date(timestamp * 1000);
    }
    
    return date.toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });
  };

  if (loading) {
    return (
      <div style={{ minHeight: '100vh', background: '#f5f5f5', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
        <div style={{ textAlign: 'center' }}>
          <div className="spinner" style={{ marginBottom: '16px' }}></div>
          <p style={{ color: '#666' }}>Loading project...</p>
        </div>
      </div>
    );
  }

  if (error || !project) {
    return (
      <div style={{ minHeight: '100vh', background: '#f5f5f5', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
        <div className="card" style={{ maxWidth: '400px', textAlign: 'center' }}>
          <div style={{ padding: '40px' }}>
            <h2 style={{ fontSize: '20px', marginBottom: '8px' }}>Error</h2>
            <p style={{ color: '#666', marginBottom: '20px' }}>{error || 'Project not found'}</p>
            <button onClick={handleBack} className="btn btn-primary">
              Back to Dashboard
            </button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div style={{ minHeight: '100vh', background: '#f5f5f5' }}>
      {/* Header */}
      <header style={{ 
        background: 'white', 
        borderBottom: '1px solid #ddd',
        padding: '16px 0'
      }}>
        <div className="container">
          <div style={{ 
            display: 'flex', 
            alignItems: 'center', 
            justifyContent: 'space-between' 
          }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>
              <button 
                onClick={handleBack}
                className="btn btn-ghost"
                style={{ padding: '8px 12px', fontSize: '14px' }}
              >
                ← Back
              </button>
              <div>
                <h1 style={{ fontSize: '20px', fontWeight: '600', marginBottom: '2px' }}>
                  {project.ProjectName}
                </h1>
                {project.Description && (
                  <p style={{ color: '#666', fontSize: '14px' }}>{project.Description}</p>
                )}
              </div>
            </div>
            
            <div style={{ 
              display: 'flex', 
              alignItems: 'center', 
              gap: '20px', 
              fontSize: '12px', 
              color: '#999' 
            }}>
              <span>Created {formatDate(project.CreatedTime)}</span>
              <span>Updated {formatDate(project.UpdatedTime)}</span>
            </div>
          </div>
        </div>
      </header>

      {/* Navigation Tabs */}
      <nav style={{ background: 'white', borderBottom: '1px solid #ddd' }}>
        <div className="container">
          <div style={{ display: 'flex', gap: '32px' }}>
            <button
              style={{
                display: 'flex',
                alignItems: 'center',
                gap: '8px',
                padding: '16px 4px',
                border: 'none',
                background: 'transparent',
                fontSize: '14px',
                fontWeight: '500',
                color: activeTab === 'viewer' ? '#007bff' : '#666',
                borderBottom: activeTab === 'viewer' ? '2px solid #007bff' : '2px solid transparent',
                cursor: 'pointer'
              }}
              onClick={() => setActiveTab('viewer')}
            >
              <svg style={{ width: '16px', height: '16px' }} fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4" />
              </svg>
              3D Viewer
            </button>
            
            <button
              style={{
                display: 'flex',
                alignItems: 'center',
                gap: '8px',
                padding: '16px 4px',
                border: 'none',
                background: 'transparent',
                fontSize: '14px',
                fontWeight: '500',
                color: activeTab === 'details' ? '#007bff' : '#666',
                borderBottom: activeTab === 'details' ? '2px solid #007bff' : '2px solid transparent',
                cursor: 'pointer'
              }}
              onClick={() => setActiveTab('details')}
            >
              <svg style={{ width: '16px', height: '16px' }} fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
              </svg>
              Project Details
            </button>
            
            <button
              style={{
                display: 'flex',
                alignItems: 'center',
                gap: '8px',
                padding: '16px 4px',
                border: 'none',
                background: 'transparent',
                fontSize: '14px',
                fontWeight: '500',
                color: activeTab === 'settings' ? '#007bff' : '#666',
                borderBottom: activeTab === 'settings' ? '2px solid #007bff' : '2px solid transparent',
                cursor: 'pointer'
              }}
              onClick={() => setActiveTab('settings')}
            >
              <svg style={{ width: '16px', height: '16px' }} fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
              </svg>
              Settings
            </button>
          </div>
        </div>
      </nav>

      {/* Content */}
      <main className="container" style={{ paddingTop: '32px', paddingBottom: '32px' }}>
        {activeTab === 'viewer' && (
          <div className="card">
            <div style={{ 
              padding: '24px', 
              borderBottom: '1px solid #eee',
              background: '#f9f9f9'
            }}>
              <h3 style={{ fontSize: '18px', fontWeight: '600', marginBottom: '4px' }}>
                3D Visualization
              </h3>
              <p style={{ color: '#666', fontSize: '14px' }}>
                Interactive 3D view of your AI-generated floorspace design
              </p>
            </div>
            <div style={{ padding: '0' }}>
              <Integrated3DViewer projectId={project.ProjectID} />
            </div>
          </div>
        )}

        {activeTab === 'details' && (
          <div style={{ 
            display: 'grid', 
            gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', 
            gap: '24px' 
          }}>
            <div className="card">
              <div style={{ 
                padding: '20px', 
                borderBottom: '1px solid #eee',
                background: '#f9f9f9'
              }}>
                <h3 style={{ fontSize: '18px', fontWeight: '600' }}>Project Information</h3>
              </div>
              <div style={{ padding: '24px' }}>
                <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
                  <div>
                    <label style={{ fontSize: '12px', fontWeight: '500', color: '#666', display: 'block', marginBottom: '4px' }}>
                      Project ID
                    </label>
                    <p style={{ fontFamily: 'monospace', fontSize: '14px', color: '#333' }}>
                      {project.ProjectID}
                    </p>
                  </div>
                  <div>
                    <label style={{ fontSize: '12px', fontWeight: '500', color: '#666', display: 'block', marginBottom: '4px' }}>
                      Owner
                    </label>
                    <p style={{ fontSize: '14px', color: '#333' }}>{project.UserID}</p>
                  </div>
                  <div>
                    <label style={{ fontSize: '12px', fontWeight: '500', color: '#666', display: 'block', marginBottom: '4px' }}>
                      Created
                    </label>
                    <p style={{ fontSize: '14px', color: '#333' }}>{formatDate(project.CreatedTime)}</p>
                  </div>
                  <div>
                    <label style={{ fontSize: '12px', fontWeight: '500', color: '#666', display: 'block', marginBottom: '4px' }}>
                      Last Modified
                    </label>
                    <p style={{ fontSize: '14px', color: '#333' }}>{formatDate(project.UpdatedTime)}</p>
                  </div>
                </div>
              </div>
            </div>

            <div className="card">
              <div style={{ 
                padding: '20px', 
                borderBottom: '1px solid #eee',
                background: '#f9f9f9'
              }}>
                <h3 style={{ fontSize: '18px', fontWeight: '600' }}>Building Statistics</h3>
              </div>
              <div style={{ padding: '24px' }}>
                <div style={{ 
                  display: 'grid', 
                  gridTemplateColumns: 'repeat(2, 1fr)', 
                  gap: '16px' 
                }}>
                  <div style={{ 
                    textAlign: 'center', 
                    padding: '16px', 
                    background: '#f5f5f5', 
                    borderRadius: '8px' 
                  }}>
                    <div style={{ fontSize: '24px', fontWeight: '700', color: '#007bff' }}>1</div>
                    <div style={{ fontSize: '12px', color: '#666' }}>Stories</div>
                  </div>
                  <div style={{ 
                    textAlign: 'center', 
                    padding: '16px', 
                    background: '#f5f5f5', 
                    borderRadius: '8px' 
                  }}>
                    <div style={{ fontSize: '24px', fontWeight: '700', color: '#007bff' }}>1</div>
                    <div style={{ fontSize: '12px', color: '#666' }}>Spaces</div>
                  </div>
                  <div style={{ 
                    textAlign: 'center', 
                    padding: '16px', 
                    background: '#f5f5f5', 
                    borderRadius: '8px' 
                  }}>
                    <div style={{ fontSize: '24px', fontWeight: '700', color: '#007bff' }}>1</div>
                    <div style={{ fontSize: '12px', color: '#666' }}>Windows</div>
                  </div>
                  <div style={{ 
                    textAlign: 'center', 
                    padding: '16px', 
                    background: '#f5f5f5', 
                    borderRadius: '8px' 
                  }}>
                    <div style={{ fontSize: '24px', fontWeight: '700', color: '#007bff' }}>20m²</div>
                    <div style={{ fontSize: '12px', color: '#666' }}>Floor Area</div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        )}

        {activeTab === 'settings' && (
          <div className="card" style={{ maxWidth: '600px' }}>
            <div style={{ 
              padding: '20px', 
              borderBottom: '1px solid #eee',
              background: '#f9f9f9'
            }}>
              <h3 style={{ fontSize: '18px', fontWeight: '600', marginBottom: '4px' }}>
                Project Settings
              </h3>
              <p style={{ color: '#666', fontSize: '14px' }}>
                Configure your project preferences
              </p>
            </div>
            <div style={{ padding: '24px' }}>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
                <div>
                  <label style={{ 
                    display: 'block', 
                    fontSize: '14px', 
                    fontWeight: '500', 
                    color: '#333', 
                    marginBottom: '8px' 
                  }}>
                    Project Name
                  </label>
                  <input type="text" className="input" defaultValue={project.ProjectName} />
                </div>
                <div>
                  <label style={{ 
                    display: 'block', 
                    fontSize: '14px', 
                    fontWeight: '500', 
                    color: '#333', 
                    marginBottom: '8px' 
                  }}>
                    Description
                  </label>
                  <textarea 
                    className="input" 
                    rows={3} 
                    defaultValue={project.Description}
                    style={{ resize: 'vertical' }}
                  ></textarea>
                </div>
                <div>
                  <label style={{ 
                    display: 'block', 
                    fontSize: '14px', 
                    fontWeight: '500', 
                    color: '#333', 
                    marginBottom: '8px' 
                  }}>
                    Units
                  </label>
                  <select className="input">
                    <option>Metric (SI)</option>
                    <option>Imperial (IP)</option>
                  </select>
                </div>
                <div style={{ display: 'flex', gap: '12px' }}>
                  <button className="btn btn-primary">Save Changes</button>
                  <button className="btn btn-secondary">Reset</button>
                </div>
              </div>
            </div>
          </div>
        )}
      </main>

      {/* Chatbot - Available on all tabs */}
      <Chatbot projectId={project.ProjectID} />
    </div>
  );
};

export default ProjectDetailsPage;