import { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { Project } from '../services/api';
import FloorspaceViewer from '../components/FloorspaceViewer';
import Chatbot from '../components/Chatbot';
import './ProjectDetailsPage.css';

const ProjectDetailsPage = () => {
  const { projectId } = useParams<{ projectId: string }>();
  const navigate = useNavigate();
  const [project, setProject] = useState<Project | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [activeTab, setActiveTab] = useState<'viewer' | 'details' | 'settings'>('viewer');
  const [aiGeneratedJson, setAiGeneratedJson] = useState<any>(null); // Store AI-generated JSON

  useEffect(() => {
    if (projectId) {
      fetchProject();
    }
  }, [projectId]);

  const fetchProject = async () => {
    if (!projectId) return;
    
    setLoading(true);
    setError('');
    
    try {
      // Mock project data since API might not be available
      const mockProject: Project = {
        ProjectID: projectId,
        UserID: 'mock-user',
        ProjectName: `AI Generated Room ${projectId}`,
        Description: 'Beautiful room space generated by AI with modern 3D visualization',
        CreatedTime: Date.now().toString(),
        UpdatedTime: Date.now().toString()
      };
      
      setProject(mockProject);
    } catch (err: any) {
      console.error('Error fetching project:', err);
      setError('Failed to load project. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const handleBack = () => {
    navigate('/dashboard');
  };

  // Handle JSON data from chatbot
  const handleAiJsonReceived = (jsonData: any) => {
    console.log('Received JSON from chatbot:', jsonData);
    setAiGeneratedJson(jsonData);
    
    // Switch to viewer tab to show the result
    if (activeTab !== 'viewer') {
      setActiveTab('viewer');
    }
  };

  // Clear AI-generated data
  const handleClearAiData = () => {
    setAiGeneratedJson(null);
  };

  const formatDate = (timestamp: string | number) => {
    let date: Date;
    
    if (typeof timestamp === 'string') {
      const numTimestamp = parseInt(timestamp, 10);
      if (!isNaN(numTimestamp)) {
        date = new Date(numTimestamp * 1000);
      } else {
        date = new Date(timestamp);
      }
    } else {
      date = new Date(timestamp * 1000);
    }
    
    return date.toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });
  };

  const handleExport = () => {
    if (aiGeneratedJson) {
      const dataStr = JSON.stringify(aiGeneratedJson, null, 2);
      const dataUri = 'data:application/json;charset=utf-8,'+ encodeURIComponent(dataStr);
      
      const exportFileDefaultName = `ai-generated-${projectId}.json`;
      
      const linkElement = document.createElement('a');
      linkElement.setAttribute('href', dataUri);
      linkElement.setAttribute('download', exportFileDefaultName);
      linkElement.click();
    }
  };

  if (loading) {
    return (
      <div className="project-details-page">
        <div className="loading-container">
          <div className="loading-spinner"></div>
          <p>Loading project...</p>
        </div>
      </div>
    );
  }

  if (error || !project) {
    return (
      <div className="project-details-page">
        <div className="error-container">
          <h2>Error</h2>
          <p>{error || 'Project not found'}</p>
          <button onClick={handleBack} className="btn btn-primary">
            Back to Dashboard
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="project-details-page">
      {/* Header */}
      <header className="project-header">
        <div className="header-content">
          <div className="header-left">
            <button onClick={handleBack} className="btn btn-ghost back-btn">
              ← Back
            </button>
            <div className="project-info">
              <h1>{project.ProjectName}</h1>
              {project.Description && <p>{project.Description}</p>}
            </div>
          </div>
          
          <div className="header-right">
            <span className="project-meta">Created {formatDate(project.CreatedTime)}</span>
            <span className="project-meta">Updated {formatDate(project.UpdatedTime)}</span>
          </div>
        </div>
      </header>

      {/* Navigation Tabs */}
      <nav className="project-nav">
        <div className="nav-content">
          <button
            className={`nav-tab ${activeTab === 'viewer' ? 'active' : ''}`}
            onClick={() => setActiveTab('viewer')}
          >
            <svg width="16" height="16" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4" />
            </svg>
            3D Viewer
          </button>
          
          <button
            className={`nav-tab ${activeTab === 'details' ? 'active' : ''}`}
            onClick={() => setActiveTab('details')}
          >
            <svg width="16" height="16" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
            Project Details
          </button>
          
          <button
            className={`nav-tab ${activeTab === 'settings' ? 'active' : ''}`}
            onClick={() => setActiveTab('settings')}
          >
            <svg width="16" height="16" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
            </svg>
            Settings
          </button>
        </div>
      </nav>

      {/* Content */}
      <main className="project-details-content" style={{ flex: 1, display: 'flex', flexDirection: 'column' }}>
        {activeTab === 'viewer' && (
          <div className="tab-content viewer-tab">
            <FloorspaceViewer 
              projectId={project.ProjectID} 
              externalJsonData={aiGeneratedJson}
              onClearAiData={handleClearAiData}
            />
          </div>
        )}

        {activeTab === 'details' && (
          <div className="tab-content">
            <div className="details-grid">
              <div className="details-card">
                <h3>Project Information</h3>
                <div className="details-content">
                  <div className="detail-item">
                    <label>Project ID</label>
                    <p>{project.ProjectID}</p>
                  </div>
                  <div className="detail-item">
                    <label>Owner</label>
                    <p>{project.UserID}</p>
                  </div>
                  <div className="detail-item">
                    <label>Created</label>
                    <p>{formatDate(project.CreatedTime)}</p>
                  </div>
                  <div className="detail-item">
                    <label>Last Modified</label>
                    <p>{formatDate(project.UpdatedTime)}</p>
                  </div>
                </div>
              </div>

              <div className="details-card">
                <h3>Building Statistics</h3>
                <div className="stats-grid">
                  <div className="stat-item">
                    <div className="stat-value">1</div>
                    <div className="stat-label">Stories</div>
                  </div>
                  <div className="stat-item">
                    <div className="stat-value">1</div>
                    <div className="stat-label">Spaces</div>
                  </div>
                  <div className="stat-item">
                    <div className="stat-value">1</div>
                    <div className="stat-label">Windows</div>
                  </div>
                  <div className="stat-item">
                    <div className="stat-value">20m²</div>
                    <div className="stat-label">Floor Area</div>
                  </div>
                </div>
              </div>

              {aiGeneratedJson && (
                <div className="details-card">
                  <h3>AI Generated Data</h3>
                  <div className="details-content">
                    <p>This project contains AI-generated building data.</p>
                    <button onClick={handleExport} className="btn btn-primary">
                      Export AI Data
                    </button>
                  </div>
                </div>
              )}
            </div>
          </div>
        )}

        {activeTab === 'settings' && (
          <div className="tab-content">
            <div className="settings-container">
              <div className="settings-card">
                <h3>Project Settings</h3>
                <div className="settings-content">
                  <div className="setting-item">
                    <label>Project Name</label>
                    <input type="text" defaultValue={project.ProjectName} />
                  </div>
                  <div className="setting-item">
                    <label>Description</label>
                    <textarea rows={3} defaultValue={project.Description}></textarea>
                  </div>
                  <div className="setting-item">
                    <label>Units</label>
                    <select>
                      <option>Metric (SI)</option>
                      <option>Imperial (IP)</option>
                    </select>
                  </div>
                  <div className="setting-actions">
                    <button className="btn btn-primary">Save Changes</button>
                    <button className="btn btn-secondary">Reset</button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        )}
      </main>

      {/* Chatbot - Available on all tabs */}
      <Chatbot 
        projectId={project.ProjectID} 
        onJsonReceived={handleAiJsonReceived}
      />
    </div>
  );
};

export default ProjectDetailsPage;